scenario_query/routes.py
from flask import Blueprint, render_template, current_app, request, session
from DB.sql_provider import SQLProvider
from DB.database import work_with_db

from access import group_permission_decorator

query_app = Blueprint('query', __name__, template_folder='templates')
provider = SQLProvider('scenario_query/sql/')


"""Шаблонная функция для каждого обработчика запроса. Принимает POST-параметры со страницы, проверяет их на пустоту и 
выполняет sql-запрос с выводом результатов на итоговую страницу"""


def func(file, rus_keys, string_value):
    value1 = request.form.get("value1", "")
    value2 = request.form.get('value2', "")
    if value1 != "" and value2 != "":
        sql = provider.get(file, sql_val1=value1, sql_val2=value2)
        result = work_with_db(current_app.config['DB_CONFIG'], sql)

        if not result:
            result_list = ['Таких записей нет.']
            eng_keys = 0
        else:
            result_list = result
            eng_keys = result[0].keys()
    else:
        result_list = ['Пустой ввод.']
        eng_keys = 0

    context = {'item_list': result_list, 'eng_keys': eng_keys, 'rus_keys': rus_keys, 'string_value': string_value,
               'profile': session.get('group_name', 'unauthorized')}
    return render_template('query_output.html', **context)


"""Обработчик выдачи страницы с меню запросов"""


@query_app.route('/')
@group_permission_decorator
def query_menu_handler():
    return render_template('query_choice.html', profile=session.get('group_name', 'unauthorized'))


"""Обработчик первого запроса, передача текста запроса и ключей."""


@query_app.route('/sql1', methods=['GET', 'POST'])
@group_permission_decorator
def query_sql1_handler():
    string_value = "Отчёт о заказе блюд"
    if request.method == 'GET':
        return render_template('query.html', string_value=string_value,
                               profile=session.get('group_name', 'unauthorized'))
    else:
        rus_keys = ['Уникальный номер блюда', 'Название блюда',
                    'Общее количество заказов блюда', 'Общая выручка от заказов блюда']
        return func('sql1.sql', rus_keys, string_value)


"""Обработчик второго запроса, передача текста запроса и ключей."""


@query_app.route('/sql2', methods=['GET', 'POST'])
def query_sql2_handler():
    string_value = "Отчёт о работе официантов"
    if request.method == 'GET':
        return render_template('query.html', string_value=string_value,
                               profile=session.get('group_name', 'unauthorized'))
    else:
        rus_keys = ['Уникальный номер официанта', 'Фамилия официанта', 'Общее количество принятых заказов',
                    'Общая сумма принятых заказов']
        return func('sql2.sql', rus_keys, string_value)


"""Обработчик третьго запроса, передача текста запроса и ключей."""


@query_app.route('/sql3', methods=['GET', 'POST'])
def query_sql3_handler():
    string_value = 'Показать сведения об официантах, ' \
             'не принявших ни одного заказа'
    if request.method == 'GET':
        return render_template('query.html', string_value=string_value,
                               profile=session.get('group_name', 'unauthorized'))
    else:
        rus_keys = ['Уникальный номер официанта', 'Фамилия официанта', 'Дата рождения',
                    'Адрес', 'Дата приёма на работу', 'Дата увольнения']
        return func('sql3.sql', rus_keys, string_value)

scenario_query/templates/query.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Restaurant</title>
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body style="background-image: url('/static/images/query.jpg'); background-size: 100%">
   <div class="black_bg">
        <div class="profile_label">
            {% if profile != 'unauthorized' %}
                {{ profile }}
            {% else %}
                Не авторизован
            {% endif %}
        </div>
    </div>

    <div class="restaurant_label">
        РЕСТОРАН
    </div>

    <div class="central_rectangle" style="background: rgba(0, 0, 0, 0);">
        <div class="main_label">
            Введите месяц и год
        </div>

        <div class="links">
            <a class="in_link_button" href="{{url_for('main_menu_handler')}}">
                Главная
            </a> >
            <a class="in_link_button" href="{{url_for('query.query_menu_handler')}}">
                Работа с запросами
            </a> >
            {{ string_value }}
        </div>

        <form action="" method="post" style="margin-top: 5%; margin-bottom: 5%">
            <label for="month"></label>
            <input type="text" placeholder="Месяц" name="value1" id="month" class="form_style">

            <label for="year"></label>
            <input type="text" placeholder="Год" name="value2" id="year" class="form_style">

            <input type="submit" value="Подтвердить" class="submit_button">
        </form>
    </div>
</body>
</html>

scenario_query/templates/query_choice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Restaurant</title>
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body style="background-image: url('/static/images/query_choice.jpg'); background-size: 100%">
    <div class="black_bg">
        <div class="profile_label">
            {% if profile != 'unauthorized' %}
                {{ profile }}
            {% else %}
                Не авторизован
            {% endif %}
        </div>
    </div>

    <div class="restaurant_label">
        РЕСТОРАН
    </div>

    <div class="central_rectangle" style="background: rgba(0, 0, 0, 0);">
        <div class="main_label">
            ВЫБЕРИТЕ ЗАПРОС
        </div>

        <div class="links"><a class="in_link_button" href="{{url_for('main_menu_handler')}}">Главная</a> > Работа с запросами</div>

        <table class="table_of_buttons" style="margin-top: 7%; margin-bottom: 7%; width: 85%">
            <tr><td><a class="in_table_button" href="{{url_for('query.query_sql1_handler')}}">Отчёт о заказе блюд</a></td></tr>

            <tr><td><a class="in_table_button" href="{{url_for('query.query_sql2_handler')}}">Отчёт о работе официантов</a></td></tr>

            <tr><td><a class="in_table_button" href="{{url_for('query.query_sql3_handler')}}">Сведения об официантах, не принявших ни одного заказа</a></td></tr>
        </table>
    </div>
</body>
</html>

scenario_query/templates/query_output.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Restaurant</title>
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body style="background-image: url('/static/images/query_output.jpg'); background-size: 100%">
    <div class="black_bg">
        <div class="profile_label">
            {% if profile != 'unauthorized' %}
                {{ profile }}
            {% else %}
                Не авторизован
            {% endif %}
        </div>
    </div>

    <div class="restaurant_label">
        РЕСТОРАН
    </div>

    <div class="central_rectangle" style="background: rgba(0, 0, 0, 0);">
        <div class="main_label">
            {{ string_value }}
        </div>

        <div class="links">
            <a class="in_link_button" href="{{url_for('main_menu_handler')}}">
                Главная
            </a> >
            <a class="in_link_button" href="{{url_for('query.query_menu_handler')}}">
                Работа с запросами
            </a> >
            Результат
        </div>

        <div style="margin-top: 3%; margin-bottom: 3%">
            {% if eng_keys == 0 %}
                <div class="regular_text">
                    {{ item_list[0] }}
                </div>
            {% else %}
                 <table class="default_table">
                    <thead>
                        <tr>
                            {% for key in rus_keys %}
                                <th>{{ key }}</th>
                            {% endfor %}
                        </tr>
                    <thead>

                    <tbody>
                        {% for item in item_list %}
                            <tr>
                                {% for key in eng_keys %}
                                    <td>{{ item[key] }}</td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    <tbody>
                </table>
            {% endif %}
        </div>
    </div>
</body>
</html>