app.py
from flask import Flask, render_template, session
from scenario_query.routes import query_app
from scenario_auth.routes import auth_app
from scenario_order.routes import order_app

import json

from access import group_permission_decorator

app = Flask(__name__)
app.register_blueprint(query_app, url_prefix='/query')
app.register_blueprint(auth_app, url_prefix='/auth')
app.register_blueprint(order_app, url_prefix='/order')

app.config['DB_CONFIG'] = json.load(open('configs/db.json', 'r'))
app.config['ACCESS_CONFIG'] = json.load(open('configs/access.json', 'r'))
app.config['SECRET_KEY'] = 'my super secret key'


"""Обработчик выдачи пользователю главного меню"""


@app.route('/')
@group_permission_decorator
def main_menu_handler():
    return render_template('main_menu.html', profile=session.get('group_name', 'unauthorized'))


"""Завершение работы. Очищение всей сессии."""


@app.route('/exit')
@group_permission_decorator
def exit_page_handler():
    session.clear()
    return render_template('work_interruption.html')


if __name__ == '__main__':
    app.run(host='127.0.0.1', port=5011)

scenario_auth/routes.py
from flask import Blueprint, session, render_template, request, current_app
from DB.sql_provider import SQLProvider
from DB.database import work_with_db
from access import group_permission_decorator


auth_app = Blueprint('auth', __name__, template_folder='templates')
provider = SQLProvider('scenario_auth/sql/')

"""Авторизация. После получения данных со страницы гарантировано их наличие, соответственно, их проверки не требуется.
Если введённые данные есть в БД, то авторизация успешна и пользователь получает необходимые ему права, иначе
требуется вводить данные снова"""


@auth_app.route('/login', methods=['GET', 'POST'])
@group_permission_decorator
def login_page_handler():
    if request.method == 'GET':
        group_name = session.get('group_name', 'unauthorized')
        return render_template('authorization.html', profile=group_name)
    else:
        login = request.form.get('login')
        password = request.form.get('password')

        sql = provider.get('login_password.sql', sql_val1=login, sql_val2=password)
        result = work_with_db(current_app.config['DB_CONFIG'], sql)

        if not result:
            message = 'Введён неверный логин или пароль!'

            return render_template('login_message.html', string_value=[], message=message)
        else:
            message = 'Вход успешно выполнен!'
            session['group_name'] = result[0]['Permission_Value']
            if result[0]['Permission_Value'] == 'waiter' or result[0]['Permission_Value'] == 'admin':
                sql = provider.get('get_waiter_data.sql', sql_val=login)
                w_id_name = work_with_db(current_app.config['DB_CONFIG'], sql)
                if w_id_name:
                    session['waiter'] = w_id_name

            return render_template('login_message.html', string_value=login, message=message,
                                   profile=result[0]['Permission_Value'])

scenario_query/routes.py
from flask import Blueprint, render_template, current_app, request, session
from DB.sql_provider import SQLProvider
from DB.database import work_with_db

from access import group_permission_decorator

query_app = Blueprint('query', __name__, template_folder='templates')
provider = SQLProvider('scenario_query/sql/')


"""Шаблонная функция для каждого обработчика запроса. Принимает POST-параметры со страницы, проверяет их на пустоту и 
выполняет sql-запрос с выводом результатов на итоговую страницу"""


def func(file, rus_keys, string_value):
    value1 = request.form.get("value1", "")
    value2 = request.form.get('value2', "")
    if value1 != "" and value2 != "":
        sql = provider.get(file, sql_val1=value1, sql_val2=value2)
        result = work_with_db(current_app.config['DB_CONFIG'], sql)

        if not result:
            result_list = ['Таких записей нет.']
            eng_keys = 0
        else:
            result_list = result
            eng_keys = result[0].keys()
    else:
        result_list = ['Пустой ввод.']
        eng_keys = 0

    context = {'item_list': result_list, 'eng_keys': eng_keys, 'rus_keys': rus_keys, 'string_value': string_value,
               'profile': session.get('group_name', 'unauthorized')}
    return render_template('query_output.html', **context)


"""Обработчик выдачи страницы с меню запросов"""


@query_app.route('/')
@group_permission_decorator
def query_menu_handler():
    return render_template('query_choice.html', profile=session.get('group_name', 'unauthorized'))


"""Обработчик первого запроса, передача текста запроса и ключей."""


@query_app.route('/sql1', methods=['GET', 'POST'])
@group_permission_decorator
def query_sql1_handler():
    string_value = "Отчёт о заказе блюд"
    if request.method == 'GET':
        return render_template('query.html', string_value=string_value,
                               profile=session.get('group_name', 'unauthorized'))
    else:
        rus_keys = ['Уникальный номер блюда', 'Название блюда',
                    'Общее количество заказов блюда', 'Общая выручка от заказов блюда']
        return func('sql1.sql', rus_keys, string_value)


"""Обработчик второго запроса, передача текста запроса и ключей."""


@query_app.route('/sql2', methods=['GET', 'POST'])
def query_sql2_handler():
    string_value = "Отчёт о работе официантов"
    if request.method == 'GET':
        return render_template('query.html', string_value=string_value,
                               profile=session.get('group_name', 'unauthorized'))
    else:
        rus_keys = ['Уникальный номер официанта', 'Фамилия официанта', 'Общее количество принятых заказов',
                    'Общая сумма принятых заказов']
        return func('sql2.sql', rus_keys, string_value)


"""Обработчик третьго запроса, передача текста запроса и ключей."""


@query_app.route('/sql3', methods=['GET', 'POST'])
def query_sql3_handler():
    string_value = 'Показать сведения об официантах, ' \
             'не принявших ни одного заказа'
    if request.method == 'GET':
        return render_template('query.html', string_value=string_value,
                               profile=session.get('group_name', 'unauthorized'))
    else:
        rus_keys = ['Уникальный номер официанта', 'Фамилия официанта', 'Дата рождения',
                    'Адрес', 'Дата приёма на работу', 'Дата увольнения']
        return func('sql3.sql', rus_keys, string_value)

templates/main_menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset = "UTF-8">
    <title>Restaurant</title>
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body style="background-image: url('/static/images/main_menu.jpg'); background-size: 100%">
        <div class="restaurant_label">
            РЕСТОРАН
        </div>

        <div class="quote">
            <blockquote>
                <p>Гордость не мешает брать чаевые, но мешает благодарить за них.</p>
                <footer>— <cite>Анри Боннар</cite></footer>
            </blockquote>
        </div>

    <div class="black_bg" style="width: 50%;">
        <div class="profile_label">
            {% if profile != 'unauthorized' %}
                {{ profile }}
            {% else %}
                Не авторизован
            {% endif %}
        </div>

        <table class="table_of_buttons">
            <tr><td><a class="in_table_button" href="{{url_for('query.query_menu_handler')}}">
                Работа с запросами
            </a></td></tr>

            <tr><td><a class="in_table_button" href="{{url_for('auth.login_page_handler')}}">
                Авторизация
            </a></td></tr>

            <tr><td><a class="in_table_button" href="{{url_for('order.table_choice_handler')}}">
                Оформление заказа
            </a></td></tr>

            <tr><td><a class="in_table_button" href="{{url_for('exit_page_handler')}}">
                Завершение работы
            </a></td></tr>
        </table>
    </div>
</body>
</html>

templates/permission_denied.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset = "UTF-8">
    <title>Restaurant</title>
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body style="background-image: url('/static/images/permission_denied.jpg'); background-size: 100%">
    <div class="black_bg">
        <div class="profile_label">
            {% if profile != 'unauthorized' %}
                {{ profile }}
            {% else %}
                Не авторизован
            {% endif %}
        </div>
    </div>

    <div class="restaurant_label">
        РЕСТОРАН
    </div>

    <div class="central_rectangle">
        <div class="main_label">
            Доступ запрещён!
        </div>

        <div class="links"><a class="in_link_button" href="{{url_for('main_menu_handler')}}">Главная</a> > Сообщение об отсутствии доступа</div>

        <div class="regular_text">Пожалуйста, авторизуйтесь через пользователя с доступом.</div>
    </div>
</body>
</html>

templates/work_interruption.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Restaurant</title>
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body style="background-image: url('/static/images/work_interruption.jpg'); background-size: 100%">
    <div class="black_bg">
    </div>

    <div class="restaurant_label">
            РЕСТОРАН
    </div>

    <div class="central_rectangle">
        <div class="main_label">
            РАБОТА ЗАВЕРШЕНА
        </div>

        <div class="links"><a class="in_link_button" href="{{url_for('main_menu_handler')}}">Главная</a> > Завершение работы</div>

        <div class="regular_text">
            Возвращайтесь снова!
        </div>
    </div>
</body>
</html>